/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class Principal extends javax.swing.JFrame {

    private Controlador controlador;
    private boolean tipoNum;    //True = inteiros, False = reais
    private CardLayout panelAtual;
    private DefaultTableModel table;
    private int contLinhasTabela;
    private Object[] linha; //Guarda a ultima linha da tabela
    private Dimension dim;

    public Principal() {

        initComponents();
        this.controlador = new Controlador();
        this.dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setTitle("Maquina Norma - Inteiros");
        //Inicializando o cardlayout, para trocar entre os JPanels
        this.tipoNum = true;
        this.panelAtual = (CardLayout) this.jPanel_valores_ops_principal.getLayout();
        this.panelAtual.show(this.jPanel_valores_ops_principal, "Jpanel_inteiros");

        //Inicializa primeira linha da tabela
        this.table = (DefaultTableModel) this.jTable_regs.getModel();
        this.linha = new Object[5];
        linha[0] = "Inicio";    //Operação
        linha[1] = "(0, 0, 1)";       //Reg A
        linha[2] = "(0, 0, 1)";       //Reg B
        linha[3] = "(0, 0, 1)";       //Reg C
        linha[4] = "(0, 0, 1)";       //Reg D
        this.table.addRow(linha);   //Adiciona a linha na tabela
        
        this.jButton_empilha.setEnabled(false);
        this.jButton_desempilha.setEnabled(false);
        this.jButton_mostrarTopo.setEnabled(false);
    }

    public void formaLinha(int[] regs) {
        int[] aux;

        for (int i = 0; i < regs.length; i++) {
            aux = this.controlador.getInfosReg(regs[i]);
            this.linha[regs[i] + 1] = "(" + aux[1] + ", " + aux[0] + ", " + aux[2] + ")";
        }

        this.table.addRow(this.linha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_valores_ops_principal = new javax.swing.JPanel();
        jPanel_inteiros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_valor_int = new javax.swing.JTextField();
        labelSinal = new javax.swing.JLabel();
        jTextField_sinal_int = new javax.swing.JTextField();
        jPanel_reais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_valor_reais = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_sinal_reais = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_divisor = new javax.swing.JTextField();
        jPanel_regs_princiapal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_regs = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton_atri_A = new javax.swing.JButton();
        jButton_atri_B = new javax.swing.JButton();
        jButton_somaAB = new javax.swing.JButton();
        jButton_somaABC = new javax.swing.JButton();
        jButton_multAB = new javax.swing.JButton();
        jButton_primo = new javax.swing.JButton();
        jButton_restoAB = new javax.swing.JButton();
        jButton_fatorial = new javax.swing.JButton();
        jButton_potenciacao = new javax.swing.JButton();
        jButton_empilha = new javax.swing.JButton();
        jButton_desempilha = new javax.swing.JButton();
        jButton_mostrarTopo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        inteiros_MN = new javax.swing.JMenuItem();
        racionais_MN = new javax.swing.JMenuItem();
        mi_Pilha = new javax.swing.JMenuItem();
        jMenu_Ajuda = new javax.swing.JMenu();
        jMenuItem_exibirAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_valores_ops_principal.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Valor do Registrador");

        jTextField_valor_int.setText("0");
        jTextField_valor_int.setInheritsPopupMenu(true);

        labelSinal.setText("Sinal do Valor");

        jTextField_sinal_int.setText("0");

        javax.swing.GroupLayout jPanel_inteirosLayout = new javax.swing.GroupLayout(jPanel_inteiros);
        jPanel_inteiros.setLayout(jPanel_inteirosLayout);
        jPanel_inteirosLayout.setHorizontalGroup(
            jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inteirosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelSinal))
                .addGap(18, 18, 18)
                .addGroup(jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_valor_int)
                    .addComponent(jTextField_sinal_int, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_inteirosLayout.setVerticalGroup(
            jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inteirosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_valor_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_inteirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSinal)
                    .addComponent(jTextField_sinal_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel_valores_ops_principal.add(jPanel_inteiros, "card_inteiros");

        jLabel3.setText("Valor do Registrador");

        jLabel5.setText("Sinal do Valor");

        jTextField_sinal_reais.setText("0");
        jTextField_sinal_reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sinal_reaisActionPerformed(evt);
            }
        });

        jLabel6.setText("Divisor");

        jTextField_divisor.setText("1");

        javax.swing.GroupLayout jPanel_reaisLayout = new javax.swing.GroupLayout(jPanel_reais);
        jPanel_reais.setLayout(jPanel_reaisLayout);
        jPanel_reaisLayout.setHorizontalGroup(
            jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_valor_reais)
                    .addComponent(jTextField_sinal_reais, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jTextField_divisor))
                .addContainerGap())
        );
        jPanel_reaisLayout.setVerticalGroup(
            jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_valor_reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_sinal_reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_reaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_valores_ops_principal.add(jPanel_reais, "card_reais");

        jTable_regs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operação", "Registrador A", "Registrador B", "Registrador C", "Registrador D"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_regs);
        if (jTable_regs.getColumnModel().getColumnCount() > 0) {
            jTable_regs.getColumnModel().getColumn(0).setResizable(false);
            jTable_regs.getColumnModel().getColumn(1).setResizable(false);
            jTable_regs.getColumnModel().getColumn(2).setResizable(false);
            jTable_regs.getColumnModel().getColumn(3).setResizable(false);
            jTable_regs.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel_regs_princiapalLayout = new javax.swing.GroupLayout(jPanel_regs_princiapal);
        jPanel_regs_princiapal.setLayout(jPanel_regs_princiapalLayout);
        jPanel_regs_princiapalLayout.setHorizontalGroup(
            jPanel_regs_princiapalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        jPanel_regs_princiapalLayout.setVerticalGroup(
            jPanel_regs_princiapalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_regs_princiapalLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setText("Operações");

        jButton_atri_A.setText("Atribuir à A");
        jButton_atri_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atri_AActionPerformed(evt);
            }
        });

        jButton_atri_B.setText("Atribuir à B");
        jButton_atri_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atri_BActionPerformed(evt);
            }
        });

        jButton_somaAB.setText("A + B");
        jButton_somaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_somaABActionPerformed(evt);
            }
        });

        jButton_somaABC.setText("A + B Usando C");
        jButton_somaABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_somaABCActionPerformed(evt);
            }
        });

        jButton_multAB.setText("A x B");
        jButton_multAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multABActionPerformed(evt);
            }
        });

        jButton_primo.setText("A é Primo");
        jButton_primo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_primoActionPerformed(evt);
            }
        });

        jButton_restoAB.setText("Resto de A / B");
        jButton_restoAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restoABActionPerformed(evt);
            }
        });

        jButton_fatorial.setText("Fatorial de A");
        jButton_fatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fatorialActionPerformed(evt);
            }
        });

        jButton_potenciacao.setText("Potenciação de 5");
        jButton_potenciacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_potenciacaoActionPerformed(evt);
            }
        });

        jButton_empilha.setText("Empilha");
        jButton_empilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empilhaActionPerformed(evt);
            }
        });

        jButton_desempilha.setText("Desempilha");
        jButton_desempilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_desempilhaActionPerformed(evt);
            }
        });

        jButton_mostrarTopo.setText("Mostrar Topo");
        jButton_mostrarTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarTopoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton_atri_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_atri_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_somaAB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_somaABC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_multAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_primo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_restoAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_fatorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_potenciacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_empilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_desempilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_mostrarTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_atri_A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_atri_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_somaAB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_somaABC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_multAB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_primo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_restoAB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_fatorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_potenciacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_empilha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_desempilha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_mostrarTopo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Números");

        inteiros_MN.setText("Inteiros");
        inteiros_MN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteiros_MNActionPerformed(evt);
            }
        });
        jMenu1.add(inteiros_MN);

        racionais_MN.setText("Racionais");
        racionais_MN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racionais_MNActionPerformed(evt);
            }
        });
        jMenu1.add(racionais_MN);

        mi_Pilha.setText("Pilha");
        mi_Pilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_PilhaActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Pilha);

        jMenuBar1.add(jMenu1);

        jMenu_Ajuda.setText("Ajuda");

        jMenuItem_exibirAjuda.setText("Exibir");
        jMenuItem_exibirAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exibirAjudaActionPerformed(evt);
            }
        });
        jMenu_Ajuda.add(jMenuItem_exibirAjuda);

        jMenuBar1.add(jMenu_Ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_valores_ops_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_regs_princiapal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_regs_princiapal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_valores_ops_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_atri_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atri_AActionPerformed
        // TODO add your handling code here:
        int valor, sinal, divisor;

        //Se estiver trabalhando com números inteiros
        if (this.tipoNum) {
            valor = Integer.valueOf(this.jTextField_valor_int.getText());
            sinal = Integer.valueOf(this.jTextField_sinal_int.getText());
            divisor = 1;
        }//Se estiver trabalhando com números reais
        else {
            valor = Integer.valueOf(this.jTextField_valor_reais.getText());
            sinal = Integer.valueOf(this.jTextField_sinal_reais.getText());
            divisor = Integer.valueOf(this.jTextField_divisor.getText());
            if (divisor == 0) {
                JOptionPane.showMessageDialog(this, "Divisor não pode ser 0!\n Alterado para 1");
                divisor = 1;
            }
        }

        this.controlador.atribuirA(valor, sinal, divisor);
        this.linha[0] = "Atribuição A";
        int[] regs = new int[1];
        regs[0] = 0;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_atri_AActionPerformed

    private void jButton_somaABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_somaABActionPerformed
        // TODO add your handling code here:
        this.controlador.somaAB();

        int[] regs = new int[2]; //Informações do Reg A para a tabela
        this.linha[0] = "A + B"; //Operação
        regs[0] = 0;
        regs[1] = 1;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_somaABActionPerformed

    private void jButton_atri_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atri_BActionPerformed
        // TODO add your handling code here:
        int valor, sinal, divisor;

        //Se estiver trabalhando com números inteiros
        if (this.tipoNum) {
            valor = Integer.valueOf(this.jTextField_valor_int.getText());
            sinal = Integer.valueOf(this.jTextField_sinal_int.getText());
            divisor = 1;
        }//Se estiver trabalhando com números reais
        else {
            valor = Integer.valueOf(this.jTextField_valor_reais.getText());
            sinal = Integer.valueOf(this.jTextField_sinal_reais.getText());
            divisor = Integer.valueOf(this.jTextField_divisor.getText());
            if (divisor == 0) {
                JOptionPane.showMessageDialog(this, "Divisor não pode ser 0!\n Alterado para 1");
                divisor = 1;
            }
        }

        this.controlador.atribuirB(valor, sinal, divisor);
        this.linha[0] = "Atribuição B"; //Operação
        int[] regs = new int[1];
        regs[0] = 1;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_atri_BActionPerformed

    private void jButton_somaABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_somaABCActionPerformed
        // TODO add your handling code here:
        this.controlador.somaABC();

        this.linha[0] = "A + B Com C"; //Operação
        int[] regs = new int[3];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_somaABCActionPerformed

    private void jButton_multABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multABActionPerformed
        // TODO add your handling code here:
        this.controlador.multAB();

        this.linha[0] = "A x B"; //Operação
        int[] regs = new int[3];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_multABActionPerformed

    private void jButton_primoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_primoActionPerformed
        // TODO add your handling code here:
        this.controlador.primoABCD();
        this.linha[0] = "A é Primo"; //Operação
        int[] linhas = new int[4];
        linhas[0] = 0;
        linhas[1] = 1;
        linhas[2] = 2;
        linhas[3] = 3;
        this.formaLinha(linhas);
    }//GEN-LAST:event_jButton_primoActionPerformed

    private void jButton_restoABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restoABActionPerformed
        // TODO add your handling code here:
        this.controlador.divAB();

        this.linha[0] = "Resto A / B"; //Operação
        int[] regs = new int[4];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        regs[3] = 3;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_restoABActionPerformed

    private void jButton_fatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fatorialActionPerformed
        // TODO add your handling code here:
        this.controlador.fatorialA();

        this.linha[0] = "A Fatorial"; //Operação
        int[] regs = new int[2];
        regs[0] = 0;
        regs[1] = 2;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_fatorialActionPerformed

    private void inteiros_MNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inteiros_MNActionPerformed
        // TODO add your handling code here:
        
        this.tipoNum = true;
        this.panelAtual.show(this.jPanel_valores_ops_principal, "card_inteiros");
        this.jButton_fatorial.setEnabled(true);
        this.jButton_primo.setEnabled(true);
        this.jButton_potenciacao.setEnabled(true);
        this.jButton_atri_A.setEnabled(true);
        this.jButton_atri_B.setEnabled(true);
        this.jButton_somaAB.setEnabled(true);
        this.jButton_somaABC.setEnabled(true);
        this.jButton_multAB.setEnabled(true);
        this.jButton_restoAB.setEnabled(true);

        this.jButton_empilha.setEnabled(false);
        this.jButton_desempilha.setEnabled(false);
        this.jButton_mostrarTopo.setEnabled(false);

        this.labelSinal.setVisible(true);
        this.jTextField_sinal_int.setVisible(true);

        this.setTitle("Maquina Norma - Inteiros");
        this.jTextField_divisor.setText("1");
        this.controlador.zeraMaquina();
        this.linha[0] = "Reset"; //Operação
        
        int[] regs = new int[4];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        regs[3] = 3;
        this.formaLinha(regs);
    }//GEN-LAST:event_inteiros_MNActionPerformed

    private void racionais_MNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racionais_MNActionPerformed
        // TODO add your handling code here:
        if (!this.tipoNum) {
            return;
        }
        this.tipoNum = false;
        this.panelAtual.show(this.jPanel_valores_ops_principal, "card_reais");
        this.jButton_fatorial.setEnabled(false);
        this.jButton_primo.setEnabled(false);
        this.jButton_potenciacao.setEnabled(false);
        this.jButton_atri_A.setEnabled(true);
        this.jButton_atri_B.setEnabled(true);
        this.jButton_somaAB.setEnabled(true);
        this.jButton_somaABC.setEnabled(true);
        this.jButton_multAB.setEnabled(true);
        this.jButton_restoAB.setEnabled(true);

        this.jButton_empilha.setEnabled(false);
        this.jButton_desempilha.setEnabled(false);
        this.jButton_mostrarTopo.setEnabled(false);
        this.setTitle("Maquina Norma - Racionais");
        this.controlador.zeraMaquina();
        this.linha[0] = "Reset"; //Operação
        int[] regs = new int[4];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        regs[3] = 3;
        this.formaLinha(regs);
    }//GEN-LAST:event_racionais_MNActionPerformed

    private void jTextField_sinal_reaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sinal_reaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sinal_reaisActionPerformed

    private void jButton_potenciacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_potenciacaoActionPerformed
        // TODO add your handling code here:
        this.controlador.potenciacaoAB();

        this.linha[0] = "Potenciacao de 5"; //Operação
        int[] regs = new int[3];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        this.formaLinha(regs);
    }//GEN-LAST:event_jButton_potenciacaoActionPerformed

    private void jMenuItem_exibirAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exibirAjudaActionPerformed
        JOptionPane.showMessageDialog(this, "A interface mostra 4 registradores. Cada um é definido por"
                + "tres registradores da máquina: (S,N,D), onde\n"
                + "S: representa o sinal (0 para (+) e 1 para (-) );\n"
                + "N: representa o numerador;\n"
                + "D: representa o divisor;\n\n"
                + "A maquina permite trabalhar com numeros inteiros"
                + "e numeros racionais. Para números inteiros, o divisor sempre será 1.\n"
                + "Algumas macros estão desabilitadas para números racionais (fatorial, potenciação e verificação de número primo)"
                + " pois elas só fazem\n sentido com inteiros. Quando troca a representação os registradores são zerados\n\n"
                + "Operações:\n"
                + "Atribuir ao A ou B: Utiliza os campos de entrada para setar os valores dos registradores A ou B.\n"
                + "A + B: Atribui o valor da soma dos valores de A e B ao registrador A (perde o valor de B).\n"
                + "A + B usando C: Ultilza o registrador C para recuperar o valor de B na soma de A com B.\n"
                + "A x B: computa a multiplicação de A com B e armazena o resultado em A, ultilizando os registradores C e D para recuperar o valor de B\n"
                + "A é primo: Faz a verificação se o valor absoluto do registrador A é primo (Mensagem na tela)(apenas Inteiros).\n"
                + "Resto de A / B: Atribui o resto da divisão entre A e B para o registrador A e o resultado da divisão ao registrador C.\n"
                + "Fatorial de A: Armazena em A o resultado do fatorial do número antes da operação (Utiliza C, perdendo o valor anterior)(apenas Inteiros).\n"
                + "Potenciação de 5: calcula 5 elevado ao conteúdo de A e armazena o resultado em A (apenas Inteiros).");

    }//GEN-LAST:event_jMenuItem_exibirAjudaActionPerformed

    private void mi_PilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_PilhaActionPerformed
        // TODO add your handling code here:

        this.panelAtual.show(this.jPanel_valores_ops_principal, "card_inteiros");
        this.jButton_fatorial.setEnabled(false);
        this.jButton_primo.setEnabled(false);
        this.jButton_potenciacao.setEnabled(false);
        this.jButton_atri_A.setEnabled(false);
        this.jButton_atri_B.setEnabled(false);
        this.jButton_somaAB.setEnabled(false);
        this.jButton_somaABC.setEnabled(false);
        this.jButton_multAB.setEnabled(false);
        this.jButton_restoAB.setEnabled(false);

        this.jButton_empilha.setEnabled(true);
        this.jButton_desempilha.setEnabled(true);
        this.jButton_mostrarTopo.setEnabled(true);
        this.setTitle("Maquina Norma - Pilha");
        this.jTextField_divisor.setText("1");

        this.labelSinal.setVisible(false);
        this.jTextField_sinal_int.setVisible(false);
        this.controlador.inicializaPilha();
        this.linha[0] = "Inicializa Pilha"; //Operação
        int[] regs = new int[4];
        regs[0] = 0;
        regs[1] = 1;
        regs[2] = 2;
        regs[3] = 3;
        this.formaLinha(regs);
        
    }//GEN-LAST:event_mi_PilhaActionPerformed

    private void jButton_empilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empilhaActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(this.jTextField_valor_int.getText());

        if (num < 0) {
            num = num * (-1);
        }
        
        this.controlador.empilha(num);
        this.linha[0] = "Empilha";
        int[] linhas = new int[2];
        linhas[0] = 0;
        linhas[1] = 1;
        
        this.formaLinha(linhas);
    }//GEN-LAST:event_jButton_empilhaActionPerformed

    private void jButton_desempilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_desempilhaActionPerformed
        // TODO add your handling code here:
        int num = this.controlador.desempilha();
        this.linha[0] = "Desempilha";
        int[] linhas = new int[2];
        linhas[0] = 0;
        linhas[1] = 1;
        
        this.formaLinha(linhas);
        JOptionPane.showMessageDialog(this,"Valor removido do topo: " + num);
    }//GEN-LAST:event_jButton_desempilhaActionPerformed

    private void jButton_mostrarTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarTopoActionPerformed
        int num = this.controlador.topoPilha();
        
        JOptionPane.showMessageDialog(this,"Topo da pilha: " + num);
    }//GEN-LAST:event_jButton_mostrarTopoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem inteiros_MN;
    private javax.swing.JButton jButton_atri_A;
    private javax.swing.JButton jButton_atri_B;
    private javax.swing.JButton jButton_desempilha;
    private javax.swing.JButton jButton_empilha;
    private javax.swing.JButton jButton_fatorial;
    private javax.swing.JButton jButton_mostrarTopo;
    private javax.swing.JButton jButton_multAB;
    private javax.swing.JButton jButton_potenciacao;
    private javax.swing.JButton jButton_primo;
    private javax.swing.JButton jButton_restoAB;
    private javax.swing.JButton jButton_somaAB;
    private javax.swing.JButton jButton_somaABC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_exibirAjuda;
    private javax.swing.JMenu jMenu_Ajuda;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_inteiros;
    private javax.swing.JPanel jPanel_reais;
    private javax.swing.JPanel jPanel_regs_princiapal;
    private javax.swing.JPanel jPanel_valores_ops_principal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_regs;
    private javax.swing.JTextField jTextField_divisor;
    private javax.swing.JTextField jTextField_sinal_int;
    private javax.swing.JTextField jTextField_sinal_reais;
    private javax.swing.JTextField jTextField_valor_int;
    private javax.swing.JTextField jTextField_valor_reais;
    private javax.swing.JLabel labelSinal;
    private javax.swing.JMenuItem mi_Pilha;
    private javax.swing.JMenuItem racionais_MN;
    // End of variables declaration//GEN-END:variables
}
